---
title: "Lab of the 24th"
format: html
editor: visual
execute :
  keep-md: true
  echo: FALSE
  warning: false
---

```{r, results='hide'}
#Setup

here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(labelled)
library(viridis)
library(RColorBrewer)
```

<center>

# Dplyr-Lab (Lab of the 24th)

</center>

<center>GitHub link (URL) : <https://github.com/CBZ1310/r-101-grade-analysis></center>

## Exercise 1

### Question 1

```{r}
grades <- read_csv("grades.csv")

```

```{r,results='hide'}
Vn<- names(grades)
Vn
```

### Question 2

```{r}
rst <- grades %>% 
  summarize("Min" = min(Exam, na.rm = TRUE), 
            "Median" = median(Exam, na.rm = TRUE), 
            "Max" = max(Exam, na.rm = TRUE), 
            "Mean" = mean(Exam, na.rm = TRUE), 
            "Standard Deviation" = sd(Exam, na.rm = TRUE))

var_label(rst) <- "Exam's result mean statistics"

knitr::kable(rst, caption = "Exams - statistics", format="html", align = "c", digits = 2) %>%
  kable_minimal()


```

```{r}
cv_exam <- sd(grades$Exam, na.rm = TRUE)/mean(grades$Exam, na.rm = TRUE)*100
var_label(cv_exam)<- "Coefficient of variation of the exam's grades"

cat("Complementary data - Coefficient of variation =", cv_exam,"%")
```

### Question 3

```{r}
Dnc <- sum(is.na(grades$Exam))
                         
var_label(Dnc) <- "Do not come to the exam"

cat(Dnc, "students do not come at the exam")
```

### Question 4

```{r}
ggplot(grades, aes(x = Exam)) + 
  geom_bar(fill="pink")+ 
  geom_label(stat = "count", aes(label = ..count..), fill = "pink", color = "black", size = 2.5, vjust = -0.3, label.padding = unit(0.2, "lines")) + 
  labs(title = "Distribution of the Grades", x="Grades", y="Count")+
  theme(plot.title = element_text(hjust = 0.5))+
  theme_minimal()
```

```{r}
ggplot(grades, aes(x = Exam, y= "count")) +
  geom_boxplot(fill="pink") +
  labs(title = "Distribution of the Grades", x = "Grades", y = "Count") +
  theme_minimal()
```

### Question 5

```{r, results='hide'}
Vn
```

```{r}
Nst <- grades %>%
  filter(!is.na(Exam)) %>%
  group_by(Group) %>% 
  summarize(Count=n()) %>%
  arrange(desc(Count))

var_label(Nst) <- "Number of student"

knitr::kable(Nst, caption = "Number of students by group", format = "html", align = "c", digits = 2) %>%
  kable_minimal()
```

### Question 6

```{r}
ggplot(grades, aes(x=Group)) + geom_bar(fill="white") + labs(title ="Number of students by group", x="Group", y="count")
```

### Question 7

```{r}
ggplot(grades, aes(x=Group,y=Exam, color=Group)) + geom_point()+ labs(title ="Grade by group", x="Group", y="count")+theme_dark()+ theme(legend.position = "none",axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
ggplot(grades, aes(x=Group,y=Exam, fill=Group)) + geom_boxplot()+ labs(title ="Grade by group", x="Group", y="Grades")+theme_dark()+ theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1))
```

### Question 8

```{r}

G_Dnc <- grades %>%
  group_by(Group) %>%
  summarize(Missing_Exam = sum(is.na(Exam)))

                         
var_label(G_Dnc) <- "Do not come to the exam by Group "

knitr::kable(Nst, caption = "Number of students having missing exam by group", format = "markdown")
```

### Question

### Question 10

### Question

### Question
